### GENERAL VARIABLES ###

# Mandatory files
singularity_image: "/storage/replicated/cirad/projects/GE2POP/2023_LRR/LRRtransfer_image/v2_20250407/LRRtransfer.sif"
target_genome:     "GeneModelTransfer/example/mini_dataset/DATA/target.fasta"
ref_genome:        "GeneModelTransfer/example/mini_dataset/DATA/ref.fasta"
ref_gff:           "GeneModelTransfer/example/mini_dataset/DATA/ref.gff"
ref_locus_info:    "GeneModelTransfer/example/mini_dataset/DATA/info_locus.tsv"
CL_min_sim: "0.25"
ignore_exonerate_errors: "false"

# optional folder containing a prebuild LRROME
lrrome:            ""
out_dirname: ""
out_feature_id_prefix: ""
