__default__:
    mem-per-cpu: 5G
    partition: cpu-dedicated
    account: dedicated-cpu@cirad-normal
    time: "48:00:00"
    job-name: LRRtransfer.{rule}
    output: LRRtransfer.{rule}.%j.err
    error:  LRRtransfer.{rule}.%j.out

genePrediction:
    job-name: LRRtransfer.{rule}.{wildcards.split_id}
    output: LRRtransfer.{rule}.{wildcards.split_id}.%j.err
    error:  LRRtransfer.{rule}.{wildcards.split_id}.%j.out
